apiVersion: v1
kind: Template
objects:

##### Configmap #####
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "config-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "api"
      branch: "${GIT_BRANCH}"
      promotion-group: "api"
  data:
    health.xml: |+
      <auths enabled="1">
        <auth token="69f2688e-4893-4b7c-a180-e7bfae6be183" name="health" family="default" enabled="1" expire="" options="">
          <api name="HealthGet"  enabled="1" options="default=allow"/>
        </auth>
      </auths>

##### Parameters #####

parameters:
- description: The git branch
  displayName: Git branch
  name: GIT_BRANCH
  required: true