apiVersion: v1
kind: Template
labels:
  app: api
  template: api
objects:

###### ImageStreams ######

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: Redis
    name: "redis-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      branch: "${GIT_BRANCH}"
      promotion-group: "api"
  spec:
    lookupPolicy:
      local: true


###### BuildConfig #####

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "redis-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      branch: "${GIT_BRANCH}"
      promotion-group: "api"
  spec:
    source:
      type: "Dockerfile"
      dockerfile: "FROM redis:4-alpine\nUSER 1001"
    strategy:
      dockerStrategy: {}
    triggers:
      - type: "ConfigChange"
    output:
      to:
        kind: "ImageStreamTag"
        name: "redis-${GIT_BRANCH}:latest"

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "deploy-api-${GIT_BRANCH}"
    labels:
      name: "deploy-api-${GIT_BRANCH}"
      branch: "${GIT_BRANCH}"
  spec:
    source:
      git:
        uri: "${GIT_URL}"
        ref: "${GIT_BRANCH}"
      sourceSecret:
        name: "target-git"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: "./install/jenkinsfiles/develop.groovy"
        env:
          - name: GIT_BRANCH
            value: "${GIT_BRANCH}"
          - name: API_FOLDER
            value: "${API_FOLDER}"

###### Secrets ######

- apiVersion: v1
  kind: Secret
  stringData:
    password: ${GIT_TOKEN}
    username: ${GIT_USER}
  metadata:
    name: target-git
  type: kubernetes.io/basic-auth

- apiVersion: v1
  kind: Secret
  stringData:
    password: ${FLASKIT_GIT_TOKEN}
    username: ${FLASKIT_GIT_USER}
  metadata:
    name: flaskit-git
  type: kubernetes.io/basic-auth

###### Parameters ######

parameters:
- description: The target git user
  displayName: Target git user
  name: GIT_USER
  required: true
- description: The target git token
  displayName: Target git token
  name: GIT_TOKEN
  required: true
- description: The git url
  displayName: git url
  name: GIT_URL
  required: true
- description: The git branch
  displayName: git branch
  name: GIT_BRANCH
  required: true
- description: The flaskit git user
  displayName: flaskit git user
  name: FLASKIT_GIT_USER
  required: true
- description: The flaskit git token
  displayName: flaskit git token
  name: FLASKIT_GIT_TOKEN
  required: true
- description: The flaskit git url
  displayName: flaskit git url
  name: FLASKIT_GIT_URL
  required: true
- description: The flaskit git branch
  displayName: flaskit git branch
  name: FLASKIT_GIT_BRANCH
  required: true