services:
  amazingresources:
    build:
      context: .
      dockerfile: install/Dockerfile-worker-amazingresources
    depends_on:
    - redis
    environment:
      REDIS_DB: '1'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    image: adeo/worker-amazingresources
  api:
    build:
      context: .
      dockerfile: install/Dockerfile-api
    depends_on:
    - redis
    environment:
      REDIS_DB: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
    image: adeo/api-vga-api
    ports:
    - 5000:5000
    restart: always
  redis:
    command:
    - redis-server
    - --port
    - '6379'
    image: redis:4
    restart: always
version: '3'
