import os
from setuptools import setup

requirements_dir = os.path.dirname(os.path.realpath(__file__))
requirements_file = requirements_dir + '/requirements.txt'

with open(requirements_file, 'r') as fd:
    requirements = fd.read().split('\n')

setup(name='consumer',
      version='0.1',
      description='An api generated by flaskit',
      author='Author',
      author_email='author@mail.com',
      license='Adeo',
      packages=['consumer'],
      install_requires=requirements,
      scripts=['consumer/bin/run-worker', 'consumer/bin/run-tasks'],
      zip_safe=False)
